#!/bin/bash
echo "start_server script run"
cd /home/ec2-user/ruby-on-rails

db_name=$(aws ssm get-parameters --region us-west-2 --names lelik9-db-name  --with-decryption --query Parameters[0].Value)
db_name=`echo $db_name | sed -e 's/^"//' -e 's/"$//'`

db_user=$(aws ssm get-parameters --region us-west-2 --names lelik9-db-user  --with-decryption --query Parameters[0].Value)
db_user=`echo $db_user | sed -e 's/^"//' -e 's/"$//'`

db_password=$(aws ssm get-parameters --region us-west-2 --names lelik9-db-password  --with-decryption --query Parameters[0].Value)
db_password=`echo $db_password | sed -e 's/^"//' -e 's/"$//'`

db_host=$(aws ssm get-parameters --region us-west-2 --names lelik9-db-host  --with-decryption --query Parameters[0].Value)
db_host=`echo $db_host | sed -e 's/^"//' -e 's/"$//'`

export DATABASE=$db_name
export DATABASE_USERNAME=$db_user
export DATABASE_PASSWORD=$db_password
export DATABASE_HOST=$db_host
export RAILS_ENV=production
export RAKE_ENV=production
export DEVISE_SECRET=8db1b8d5158b97eb7b54bf002765323c04a5c1be86d34b44548637f6e7a358e160a078390957e5481b069761e8b8c1dcd0489cb0fa2ab302071d878634878161
export SECRET_KEY_BASE="$(bundle exec rake secret)"
export DAEMONIZE_PUMA=true
export PORT=80

gem install bundler
bundle install
bundle exec rake db:migrate
bundle exec puma
